print(not None)
print(not False)
print(not 0)
print(not 0.0)
print(not 0j)  # complex number
print(not 0b0)
print(not 0o0)
print(not 0x0)
print(not "")
print(not ())
print(not [])
print(not {})
print(not set())
print(not range(0))
